### ISSUE TITLE
Incorrect langid model in release v2.0.0-alpha.3

### ISSUE THREAD

**Issue by rggdmonk** [hplt-project/warc2text-runner#10]
The most recent [release v2.0.0-alpha.3](https://github.com/hplt-project/warc2text-runner/releases/tag/v2.0.0-alpha.3) seems to have an incorrect model.

It downloads model from https://github.com/hplt-project/warc2text-runner/releases/tag/v2.0.0-alpha.1

https://github.com/hplt-project/warc2text-runner/blob/fb881caea3d3ca18d41167c99c0b69170094a32d/src/warc2text_runner/two/stage2download.sh#L4

**Comment by nvanva** [comment]
Thank you for noticing! I've created the final v.2.0.0 release containing the code currently running on LUMI. So this issue in alpha.3 is not relevant anymore.
