### ISSUE TITLE
LangID output different in pull request and current version

### ISSUE THREAD

**Issue by rggdmonk** [hplt-project/warc2text-runner#11]
The script `traf.py` might generate `None` at multiple points.

https://github.com/hplt-project/warc2text-runner/blob/5e2f7e70aa2e27af810c8325ca0a8f625cb93d2e/src/warc2text_runner/two/trafilatura/traf.py#L28-L72

In merge request https://github.com/hplt-project/warc2text-runner/commit/61a88c7daf9e7765d8a2b85094c1f1feadcf8090 . LangID logic was: 
```
{"lang":["langcode1", "langcode2", "langcode3"],"prob":[0.9975,0.0004,0.0004]} # regular case
{"lang":null} # get None from "t" field
{"lang":["_unk"]} # get empty string from "t" field
```

In https://github.com/hplt-project/warc2text-runner/commit/fb881caea3d3ca18d41167c99c0b69170094a32d it transformed to

```
{"lang":["langcode1", "langcode2", "langcode3"],"prob":[0.9975,0.0004,0.0004]} # regular case
{"lang":null} # get None from "t" field
{"lang":null} # get empty string from "t" field
```

In the earlier logic, if you encounter `"_unk"`, it could indicate that `traf.py` might have "overcleaned" the data. However, currently, it's challenging to determine without logs if it's `None` due to an error or overcleaning.

**Comment by ZJaume** [comment]
I don't think langid has to be responsible of telling us if the text was empty or `None`.

**Comment by nvanva** [comment]
There was a comment about that in the Jaume's review for the pull request, which was not addressed or answered in the final pull request. So I took the responsibility to fix that to avoid one more iteration and delays. I agree that from the lid side it shouldn't matter of the text is null or empty, it is absent anyway. And we can always check the text field to get this info. Sorry if there are other opinions on that, but I feel this is not an important thing to delay the start of stage 2.

**Comment by rggdmonk** [comment]
Without log files, `traf.py` is akin to a black box. For any statistical analysis, we don't just need output, but also the log files.

This situation could be compared to shooting ourselves in the foot.

**Comment by nvanva** [comment]
Sorry, I don't fully understand, could you explain more? What is the difference between checking text.zst and lang.zst to calculate the proportion of null and empty texts?

**Comment by rggdmonk** [comment]
> Sorry, I don't fully understand, could you explain more?

It's unclear why the existing logic was abruptly changed without prior testing. 

> What is the difference between checking text.zst and lang.zst to calculate the proportion of null and empty texts?

You need to use both text.zst and lang.zst, not just lang.zst.

**Comment by nvanva** [comment]
Yes, you have to use text.zst to calculate statistics for texts extracted by Trafilatura. And lang.zst should be used to calculate statistics related to the languages identified. Like Jaume, I don't see why everything should be put to lang.zst. 

Could you please more clearly explain what are the concrete problems you see with the current code we are running on LUMI now? This issue you opened is about the difference between the pull request and the current code, I don't see why this small fix in the output format is an issue.

**Comment by nvanva** [comment]
After talking to @rggdmonk we figured out that the problem was in an incorrect diagram of stage2 he had that did not reflect the fact that the outputs of traf.py are dumped to text.zst files, which can be used for statistical analysis of Trafilatura outputs. Thus, I'm closing this issue.

**Comment by rggdmonk** [comment]
@nvanva 

`traf.py` produce only JSON-encoded lines printed to the standard output. Not files.
`traf.py` and `proto_langid.py` communicate only this way.

https://github.com/hplt-project/warc2text-runner/blob/45dbf512764a5ba754ff516f471dc269239fd4d0/src/warc2text_runner/two/stage2local.sh#L23C1-L27C97

What concerns me is the sudden change in the output format that was proposed in March, just hours before the “run”.

**Comment by nvanva** [comment]
tee >(zstd > ${OUTDIR}/text.zst) 
This command on the lines you pointed to dumps outputs of traf.py to text.zst
